### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by zhengzaixiazai** [craftzdog/vlog-translator#1]
I buid a docker image and deploy it on the server, but isn't sucsessfull, 

Downloading audio...
Transcribing audio. It takes a while...
[Error] Traceback (most recent call last):
[Error]   File "/app/scripts/transcribe.py", line 8, in <module>
[Error] [Error]     audio_file = open(audio_file_path, "rb")
[Error] FileNotFoundError: [Errno 2] No such file or directory: '/app/tmp/ZBorDL608PQ.m4a'
[Error] 
Translating text...

Done!

on local env, it still run error:
D:\vlog-translator>npm run dev

> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\vlog-translator\.env
event - compiled client and server successfully in 446 ms (163 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 187 ms (204 modules)
wait  - compiling /api/audio (client and server)...
event - compiled successfully in 37 ms (58 modules)
video ID: Aa83vRghue4
error - Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at spawn (node:child_process:757:9)
    at GET (webpack-internal:///(api)/./pages/api/audio.ts:22:69)
    at Object.apiResolver (D:\vlog-translator\node_modules\next\dist\server\api-utils\node.js:372:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevServer.runApi (D:\vlog-translator\node_modules\next\dist\server\next-server.js:514:9)
    at async Object.fn (D:\\vlog-translator\node_modules\next\dist\server\next-server.js:828:35)
    at async Router.execute (D:\vlog-translator\node_modules\next\dist\server\router.js:243:32)
    at async DevServer.runImpl (D:\vlog-translator\node_modules\next\dist\server\base-server.js:432:29)
    at async DevServer.run (D:\vlog-translator\node_modules\next\dist\server\dev\next-dev-server.js:831:20)
    at async DevServer.handleRequestImpl (D:\vlog-translator\node_modules\next\dist\server\base-server.js:375:20)
    at async D:\vlog-translator\node_modules\next\dist\server\base-server.js:157:99 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn',
  page: '/api/audio'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 76 ms (217 modules)
wait  - compiling /api/transcript (client and server)...
event - compiled successfully in 31 ms (59 modules)
video ID: Aa83vRghue4
Finished command. Exit code: 9009

**Comment by craftzdog** [comment]
install python3
